<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><?codewarrior exportversion="2.0" ideversion="5.8" ?><!DOCTYPE PROJECT [<!ELEMENT PROJECT (TARGETLIST, TARGETORDER, GROUPLIST, DESIGNLIST?)><!ELEMENT TARGETLIST (TARGET+)><!ELEMENT TARGET (NAME, SETTINGLIST, FILELIST?, LINKORDER?, SEGMENTLIST?, OVERLAYGROUPLIST?, SUBTARGETLIST?, SUBPROJECTLIST?, FRAMEWORKLIST?, PACKAGEACTIONSLIST?)><!ELEMENT NAME (#PCDATA)><!ELEMENT USERSOURCETREETYPE (#PCDATA)><!ELEMENT PATH (#PCDATA)><!ELEMENT FILELIST (FILE*)><!ELEMENT FILE (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?, ROOTFILEREF?, FILEKIND?, FILEFLAGS?)><!ELEMENT PATHTYPE (#PCDATA)><!ELEMENT PATHROOT (#PCDATA)><!ELEMENT ACCESSPATH (#PCDATA)><!ELEMENT PATHFORMAT (#PCDATA)><!ELEMENT ROOTFILEREF (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)><!ELEMENT FILEKIND (#PCDATA)><!ELEMENT FILEFLAGS (#PCDATA)><!ELEMENT FILEREF (TARGETNAME?, PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)><!ELEMENT TARGETNAME (#PCDATA)><!ELEMENT SETTINGLIST ((SETTING|PANELDATA)+)><!ELEMENT SETTING (NAME?, (VALUE|(SETTING+)))><!ELEMENT PANELDATA (NAME, VALUE)><!ELEMENT VALUE (#PCDATA)><!ELEMENT LINKORDER (FILEREF*)><!ELEMENT SEGMENTLIST (SEGMENT+)><!ELEMENT SEGMENT (NAME, ATTRIBUTES?, FILEREF*)><!ELEMENT ATTRIBUTES (#PCDATA)><!ELEMENT OVERLAYGROUPLIST (OVERLAYGROUP+)><!ELEMENT OVERLAYGROUP (NAME, BASEADDRESS, OVERLAY*)><!ELEMENT BASEADDRESS (#PCDATA)><!ELEMENT OVERLAY (NAME, FILEREF*)><!ELEMENT SUBTARGETLIST (SUBTARGET+)><!ELEMENT TARGETOUTPUTNAME (#PCDATA)><!ELEMENT TARGETOUTPUTDISPLAYNAME (#PCDATA)><!ELEMENT TARGETOUTPUTPATHFORMAT (#PCDATA)><!ELEMENT TARGETOUTPUTACCESSTYPE (#PCDATA)><!ELEMENT SUBTARGET (TARGETNAME, ATTRIBUTES?, TARGETOUTPUTNAME?, TARGETOUTPUTDISPLAYNAME?, TARGETOUTPUTPATHFORMAT?, TARGETOUTPUTACCESSTYPE?, FILEREF?)><!ELEMENT SUBPROJECTLIST (SUBPROJECT+)><!ELEMENT SUBPROJECT (FILEREF, SUBPROJECTTARGETLIST)><!ELEMENT SUBPROJECTTARGETLIST (SUBPROJECTTARGET*)><!ELEMENT SUBPROJECTTARGET (TARGETNAME, ATTRIBUTES?, FILEREF?)><!ELEMENT FRAMEWORKLIST (FRAMEWORK+)><!ELEMENT FRAMEWORK (FILEREF, DYNAMICLIBRARY?, VERSION?)><!ELEMENT PACKAGEACTIONSLIST (PACKAGEACTION+)><!ELEMENT PACKAGEACTION (#PCDATA)><!ELEMENT LIBRARYFILE (FILEREF)><!ELEMENT VERSION (#PCDATA)><!ELEMENT TARGETORDER (ORDEREDTARGET|ORDEREDDESIGN)*><!ELEMENT ORDEREDTARGET (NAME)><!ELEMENT ORDEREDDESIGN (NAME, ORDEREDTARGET+)><!ELEMENT GROUPLIST (GROUP|FILEREF)*><!ELEMENT GROUP (NAME, (GROUP|FILEREF)*)><!ELEMENT DESIGNLIST (DESIGN+)><!ELEMENT DESIGN (NAME, DESIGNDATA)><!ELEMENT DESIGNDATA (#PCDATA)>]><PROJECT>    <TARGETLIST>        <TARGET>            <NAME>QTTimeCodec58macppc</NAME>            <SETTINGLIST>                <!-- Settings for "Source Trees" panel -->                <SETTING><NAME>UserSourceTrees</NAME><VALUE></VALUE></SETTING>                <!-- Settings for "Access Paths" panel -->                <SETTING><NAME>AlwaysSearchUserPaths</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>InterpretDOSAndUnixPaths</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>RequireFrameworkStyleIncludes</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>SourceRelativeIncludes</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>UserSearchPaths</NAME>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>source</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>Unix</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>source/mac</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>Unix</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>source/windows</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>Unix</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                </SETTING>                <SETTING><NAME>SystemSearchPaths</NAME>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                </SETTING>                <!-- Settings for "Debugger Runtime" panel -->                <SETTING><NAME>MWRuntimeSettings_WorkingDirectory</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>MWRuntimeSettings_CommandLine</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>MWRuntimeSettings_HostApplication</NAME>                    <SETTING><NAME>Path</NAME><VALUE></VALUE></SETTING>                    <SETTING><NAME>PathFormat</NAME><VALUE>Generic</VALUE></SETTING>                    <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                </SETTING>                <SETTING><NAME>MWRuntimeSettings_EnvVars</NAME><VALUE></VALUE></SETTING>                <!-- Settings for "Target Settings" panel -->                <SETTING><NAME>Linker</NAME><VALUE>MacOS PPC Linker</VALUE></SETTING>                <SETTING><NAME>PreLinker</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>PostLinker</NAME><VALUE></VALUE></SETTING>                <SETTING><NAME>Targetname</NAME><VALUE>QTTimeCodec58macppc</VALUE></SETTING>                <SETTING><NAME>OutputDirectory</NAME>                    <SETTING><NAME>Path</NAME><VALUE>bin</VALUE></SETTING>                    <SETTING><NAME>PathFormat</NAME><VALUE>Unix</VALUE></SETTING>                    <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>                </SETTING>                <SETTING><NAME>SaveEntriesUsingRelativePaths</NAME><VALUE>false</VALUE></SETTING>                <!-- Settings for "File Mappings" panel -->                <SETTING><NAME>FileMappings</NAME>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>APPL</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>Appl</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>MMLB</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Lib Import PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>Balloon Help</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>MPLF</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Lib Import PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>Balloon Help</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>MWCD</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>RSRC</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.arr</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.axp</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.bh</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Balloon Help</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.c</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.c++</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.cc</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.cp</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.cpp</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.cxx</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.exp</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.h</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.h++</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.hpp</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.hxx</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.pch</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.pch++</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.plc</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Property List Compiler</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>Property List</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.ploc</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Property List Compiler</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>Property List</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.r</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>Rez</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>Rez</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.s</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>PPCAsm</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>Balloon Help</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE>.wke</VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>XCOF</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE>XCOFF Import PPC</VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE>Balloon Help</VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>docu</VALUE></SETTING>                        <SETTING><NAME>FileExtension</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>FileType</NAME><VALUE>rsrc</VAL